version: '3.7'

services:
  votesystem:
    build: .
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    env_file:
      - .env

  votesystem_mysql:
    container_name: 'database-vs'
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3308:3306'

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vote_system
      MYSQL_USER: root
      MYSQL_PASSWORD: root
